use crate::error::{CargoJamError, Result};
use std::path::Path;

/// Initialize a git repository in the given directory
pub fn init_git_repo(path: &Path) -> Result<()> {
    git2::Repository::init(path).map_err(|e| {
        CargoJamError::Git(format!("Failed to initialize git repository: {}", e))
    })?;

    // Create initial .gitignore if it doesn't exist
    let gitignore_path = path.join(".gitignore");
    if !gitignore_path.exists() {
        let gitignore_content = r#"# Generated by Cargo
# will have compiled files and executables
debug/
target/

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb

# JAM service blobs
*.jam
"#;
        std::fs::write(&gitignore_path, gitignore_content)?;
    }

    Ok(())
}
